version: "2"
services:
    app:
        build: .
        image: miniverse
        links:
            - db
        ports:
            - "5000:5000"
    db:
#        build:
#            context: .
#            dockerfile: Dockerfile.db
        image: mysql:5.7
        restart: always
        ports:
            - "32000:3306"
        expose:
            - "32000"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: miniverse
        volumes:
            - ./db:/var/lib/mysql